// Publish-time transform: pull node scripts OUT of game.json and emit them as real functions in a
// separate game.scripts.js. The published game then loads scripts as normal JS (parsed by the browser)
// instead of eval-ing script strings from JSON at runtime.
//
// The factory body is built by the engine's buildFactoryBody — the same function the editor's eval path
// compiles through — so the two paths cannot drift apart. It is also what rewrites the script's `import`
// statements into `__cleoImport(...)` calls, since an import statement is not legal inside a function.
//
// The final source is heavily obfuscated (see generateScriptsJs) so shipped game logic is unreadable.

import { Logger, buildFactoryBody } from 'cleo';

export type ScriptMap = Record<string, string>;

// Walk the scene tree (root included) collecting `{ nodeId: script }` and stripping `script` from the
// nodes, so game.json contains no script strings.
export function extractScripts(data: any): { data: any; scripts: ScriptMap } {
  const scripts: ScriptMap = {};

  const visit = (node: any): void => {
    if (node && typeof node === 'object') {
      if (typeof node.script === 'string' && node.script.trim() && node.id) {
        scripts[node.id] = node.script;
        delete node.script;
      }
      for (const child of (node.children ?? [])) visit(child);
    }
  };

  if (data?.scene) visit(data.scene);
  return { data, scripts };
}

// Build the plain (readable) game.scripts.js source. Scripts that fail to compile are skipped (with a
// warning) so one broken script can't break the whole file's parse.
export function buildScriptsSource(scripts: ScriptMap): string {
  const lines: string[] = [
    '// Generated by Cleo publish. Node scripts as real functions (no runtime eval of JSON strings).',
    'window.CLEO_GAME_SCRIPTS = window.CLEO_GAME_SCRIPTS || {};',
  ];

  for (const [id, script] of Object.entries(scripts)) {
    let source: string;
    try {
      // buildFactoryBody throws on unsupported module syntax; `new Function` then catches plain syntax
      // errors. Either way one broken script is skipped rather than breaking the whole file's parse.
      source = `function(__cleoImport) {\n${buildFactoryBody(script)}\n}`;
      // eslint-disable-next-line no-new-func
      new Function(`return (${source});`);
    } catch (e) {
      lines.push(`// skipped script for ${id}: ${String((e as any)?.message || e).replace(/\n/g, ' ')}`);
      continue;
    }
    lines.push(`window.CLEO_GAME_SCRIPTS[${JSON.stringify(id)}] = ${source};`);
  }

  return lines.join('\n') + '\n';
}

// Aggressive-but-eval-free obfuscation. transformObjectKeys/renameGlobals are OFF on purpose so the
// public interface survives: the returned { onStart, onUpdate, ... } keys are read by the player's
// attachScripts.ts, and `window.CLEO_GAME_SCRIPTS` must keep its name. No debugProtection/selfDefending
// so we never reintroduce the Function constructor / eval.
const OBFUSCATOR_OPTIONS = {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 0.75,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 0.4,
  identifierNamesGenerator: 'hexadecimal',
  numbersToExpressions: true,
  simplify: true,
  splitStrings: true,
  splitStringsChunkLength: 6,
  stringArray: true,
  stringArrayEncoding: ['base64'],
  stringArrayThreshold: 1,
  transformObjectKeys: false,
  renameGlobals: false,
};

// Produce the shipped game.scripts.js: build the source, then heavily obfuscate it. The obfuscator is
// lazy-loaded so it code-splits out of the editor's initial bundle. If obfuscation fails for any reason,
// we fall back to the readable source rather than block a publish.
export async function generateScriptsJs(scripts: ScriptMap): Promise<string> {
  const source = buildScriptsSource(scripts);
  try {
    const mod: any = await import('javascript-obfuscator');
    const obfuscator = mod.default ?? mod;
    return obfuscator.obfuscate(source, OBFUSCATOR_OPTIONS).getObfuscatedCode() + '\n';
  } catch (e) {
    Logger.warn(`Script obfuscation failed, shipping un-obfuscated scripts: ${e}`, 'Publish');
    return source;
  }
}
