// Publish-time transform: pull node scripts OUT of game.json and emit them as real functions in a
// separate game.scripts.js. The published game then loads scripts as normal JS (parsed by the browser)
// instead of eval-ing script strings from JSON at runtime.
//
// The factory body is built by the engine's buildFactoryBody — the same function the editor's eval path
// compiles through — so the two paths cannot drift apart. It is also what rewrites the script's `import`
// statements into `__cleoImport(...)` calls, since an import statement is not legal inside a function.
//
// The source this module produces is then heavily obfuscated (see ./obfuscate) so shipped game logic is
// unreadable. Obfuscation lives in its own module because it runs in the project worker, while this one
// cannot: buildFactoryBody comes from `cleo`, and importing the engine into a worker is neither needed
// nor safe. Building the script source is cheap (a few KB of user code); obfuscating it is not.

import { buildFactoryBody } from 'cleo';

export type ScriptMap = Record<string, string>;

// Walk the scene tree (root included) collecting `{ nodeId: script }` and stripping `script` from the
// nodes, so game.json contains no script strings.
export function extractScripts(data: any): { data: any; scripts: ScriptMap } {
  const scripts: ScriptMap = {};

  const visit = (node: any): void => {
    if (node && typeof node === 'object') {
      if (typeof node.script === 'string' && node.script.trim() && node.id) {
        scripts[node.id] = node.script;
        delete node.script;
      }
      for (const child of (node.children ?? [])) visit(child);
    }
  };

  if (data?.scene) visit(data.scene);                       // v1: single scene
  if (data?.scenes) for (const s of Object.values<any>(data.scenes)) visit(s?.scene); // v2: every scene
  return { data, scripts };
}

// Build the plain (readable) game.scripts.js source. Scripts that fail to compile are skipped (with a
// warning) so one broken script can't break the whole file's parse.
export function buildScriptsSource(scripts: ScriptMap): string {
  const lines: string[] = [
    '// Generated by Cleo publish. Node scripts as real functions (no runtime eval of JSON strings).',
    'window.CLEO_GAME_SCRIPTS = window.CLEO_GAME_SCRIPTS || {};',
  ];

  for (const [id, script] of Object.entries(scripts)) {
    let source: string;
    try {
      // buildFactoryBody throws on unsupported module syntax; `new Function` then catches plain syntax
      // errors. Either way one broken script is skipped rather than breaking the whole file's parse.
      source = `function(__cleoImport) {\n${buildFactoryBody(script)}\n}`;
      // eslint-disable-next-line no-new-func
      new Function(`return (${source});`);
    } catch (e) {
      lines.push(`// skipped script for ${id}: ${String((e as any)?.message || e).replace(/\n/g, ' ')}`);
      continue;
    }
    lines.push(`window.CLEO_GAME_SCRIPTS[${JSON.stringify(id)}] = ${source};`);
  }

  return lines.join('\n') + '\n';
}

