import { Logger } from 'cleo';
import { BUNDLE_PATHS, BundleManifest } from './bundle';
import { BundleSource, readBundle } from './bundleRead';
import { applyBundleAsNewProject } from './bundleImport';
import { parseJsonBuffer } from '../workers/workerClient';

// Example projects that ship with the editor.
//
// Each one is a project bundle that was exported from a local editor and then UNZIPPED into a folder under
// `editor/public/examples/<slug>/` (see editor/tools/add-example.mjs, which does the unzipping and writes
// the index). CopyWebpackPlugin puts `public/` into `dist/`, the Firebase workflow deploys `dist/`, and the
// Electron package ships it too — so an example is just static files next to the app, with no server, no
// API and no CDN involved. It also means examples work offline on desktop.
//
// The folder is not listable over HTTP, and it does not need to be: the file set is fully derivable. The
// seven library filenames are fixed, `manifest.sceneMetas` names every scene file, and `textures/index.json`
// names every texture payload. Only the human-facing catalogue (which examples exist, what they are called)
// needs writing down, and that is `index.json`.

/** Where the example folders live, relative to the document. Matches publishClient's `fetch('player/…')`. */
const EXAMPLES_BASE = 'examples/';

/** One row of `examples/index.json`, generated by the CLI from what is actually on disk. */
export interface ExampleEntry {
  /** Folder name under examples/, and the stable identity of the example. */
  slug: string;
  name: string;
  description?: string;
  /** Path relative to EXAMPLES_BASE, e.g. `third-person-demo/thumbnail.png`. Absent when none was found. */
  thumbnail?: string;
  /** Sort key; ties fall back to name. */
  order?: number;
  /** Total size of the folder on disk — what the user is about to download. */
  bytes: number;
  sceneCount: number;
  textureCount: number;
  createdAt: number;
}

interface ExampleIndexFile {
  version: 1;
  examples: ExampleEntry[];
}

/**
 * Fetch one static file under examples/, refusing an SPA fallback.
 *
 * `editor/firebase.json` rewrites `"**" -> "/index.html"`, so a path that does not exist comes back as
 * **HTTP 200 carrying the editor's own HTML** rather than a 404. Left unchecked that turns a typo into a
 * texture made of markup, or a JSON.parse failure reading `Unexpected token '<'` with nothing to say about
 * which file was missing. So every response is checked for being HTML before it is believed.
 */
async function fetchEntry(path: string): Promise<Response | null> {
  const res = await fetch(EXAMPLES_BASE + path);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`examples/${path}: HTTP ${res.status}`);
  // The hosting rewrite always serves index.html, so content-type is the reliable tell. Real bundle entries
  // are application/json or an octet-stream; none of them is ever text/html.
  if ((res.headers.get('content-type') ?? '').includes('text/html')) return null;
  return res;
}

async function fetchJson(path: string): Promise<any | null> {
  const res = await fetchEntry(path);
  if (!res) return null;
  const text = await res.text();
  // Belt and braces: a static host with no content-type at all would slip an HTML fallback past the check
  // above, and "unexpected <" is a far worse error message than naming the file.
  if (text.trimStart().startsWith('<')) return null;
  try {
    return JSON.parse(text);
  } catch (e: any) {
    throw new Error(`examples/${path} is not valid JSON: ${e?.message ?? e}`);
  }
}

/**
 * The catalogue of bundled examples, in display order.
 *
 * A missing or malformed index is NOT an error: most checkouts ship no examples at all, and the gallery
 * simply does not appear. Only a present-but-broken index is worth a log line.
 */
export async function loadExampleIndex(): Promise<ExampleEntry[]> {
  let index: ExampleIndexFile | null = null;
  try {
    index = (await fetchJson('index.json')) as ExampleIndexFile | null;
  } catch (e: any) {
    Logger.error(`Could not read the example index: ${e?.message ?? e}`, 'Editor');
    return [];
  }
  if (!index || !Array.isArray(index.examples)) return [];
  return [...index.examples].sort(
    (a, b) => (a.order ?? 0) - (b.order ?? 0) || a.name.localeCompare(b.name),
  );
}

/** The URL an `ExampleEntry.thumbnail` resolves to, or null when the example has no image. */
export function exampleThumbnailUrl(entry: ExampleEntry): string | null {
  return entry.thumbnail ? EXAMPLES_BASE + entry.thumbnail : null;
}

/** Read one example's folder as a bundle, exactly as if its .zip had been picked from disk. */
function fetchSource(slug: string, onEntry?: (done: number, total: number) => void): BundleSource {
  const dir = `${slug}/`;
  return {
    async json(path) {
      // Scene blobs are the one big JSON in a bundle (geometry is embedded per model), so they are parsed
      // in the project worker. Everything else is small enough that the round trip would cost more than the
      // parse.
      if (!path.startsWith(BUNDLE_PATHS.scenesDir)) return fetchJson(dir + path);
      const res = await fetchEntry(dir + path);
      if (!res) return null;
      const buffer = await res.arrayBuffer();
      if (!buffer.byteLength || new Uint8Array(buffer)[0] === 0x3c) return null; // '<' = an HTML fallback
      return parseJsonBuffer(buffer);
    },
    async bytes(path) {
      const res = await fetchEntry(dir + path);
      return res ? await res.arrayBuffer() : null;
    },
    // No directory listing over HTTP, so the manifest is the authority on which scenes exist. An example is
    // always freshly exported, so its metas are always present — but falling back to nothing rather than
    // guessing keeps a malformed folder loud instead of half-loaded.
    async scenePaths(manifest: BundleManifest) {
      return (manifest.sceneMetas ?? []).map(m => `${BUNDLE_PATHS.scenesDir}${m.id}.json`);
    },
    onEntry,
  };
}

/**
 * Download a bundled example and open it as a brand-new project.
 *
 * Resolves by reloading the page (openProject), so callers should treat a resolved promise as "we are
 * leaving" rather than "we are done".
 *
 * Nothing here may touch scoped storage: the gallery also renders on the boot launcher, where no project is
 * open and `scoped()` throws by design. It holds because `applyBundleAsNewProject` mints the project first
 * and threads its id explicitly through every key helper.
 */
export async function importExample(
  entry: ExampleEntry,
  onProgress?: (fraction: number) => void,
): Promise<void> {
  const source = fetchSource(entry.slug, (done, total) => onProgress?.(total ? done / total : 0));
  const { bundle } = await readBundle(source);
  if (bundle.manifest.kind !== 'project') {
    throw new Error(`Example "${entry.slug}" is not a project bundle`);
  }
  await applyBundleAsNewProject(bundle, entry.name);
}

/** Human-readable download size for a card. */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB'];
  let value = bytes / 1024;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit++;
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`;
}
