// ---------------------------------------------------------------------------------------------------
// Per-placement animation state, carried across a rebuild.
//
// Re-instantiating a placed instance reconstructs it from its ASSET — and a model asset never carries an
// animation state machine. Machines are authored in the Animation Editor and committed onto the placed NODE,
// so they exist only inside the scene (or template) blob. Without this, any asset edit that changes a model's
// content hash silently replaces every configured character in every scene with a bare one.
//
// That is not hypothetical: assigning an IK rig wrote `skin.ikRig` into the asset, which changed its hash,
// which rebuilt every placement, which dropped every state machine. The hash now ignores skeleton metadata
// (see assetHash.ts) so that particular trigger is gone — but the rebuild must be safe regardless, because
// plenty of legitimate edits still change the hash.
//
// Deliberately ENGINE-FREE — structural types, no `cleo` import — so the root test suite can load it. That
// suite cannot resolve the editor's `cleo` → ../dist link, and this rule is the part worth testing.
// (Same reasoning as modelClips.ts and cameraRayFilter.ts.)
// ---------------------------------------------------------------------------------------------------

/** The subset of an Animator this needs. Structural, so a test can hand it a plain object. */
export interface AnimatorLike {
  getStateMachine(): any
  getAnimationMappings(): any[]
  setStateMachine(sm: any): void
  setAnimationMappings(mappings: any[]): void
}

/** The subset of a Node this needs. `animator` is present (possibly null) only on ModelNodes. */
export interface NodeLike {
  animator?: AnimatorLike | null
  ragdollConfig?: any
  /** ModelNodes only; `skin` exists only on an AnimatedModel. */
  model?: { skin?: { ikRig?: any } | null } | null
  children: NodeLike[]
}

/**
 * Push a model asset's IK rig onto every skinned model in a placed subtree.
 *
 * The rig is skeleton data owned by the ASSET, but a template stores its own serialized copy of the subtree —
 * skin and all — so a rig authored while a character was a template instance is baked into the template and
 * rebuilt from there on every load. Re-applying from the asset is what stops that copy outliving the panel
 * that wrote it.
 *
 * `undefined` is assigned, never skipped: "the asset has no rig" has to be able to clear one.
 */
export function applyIkRig(inst: NodeLike, rig: any | null): void {
  for (const node of animationNodesOf(inst)) {
    const skin = node.model?.skin
    if (skin) skin.ikRig = rig ?? undefined
  }
}

export interface PlacedAnimationState {
  stateMachine: any | null
  mappings: any[] | null
  ragdoll: any | null
}

/** Whether a node is the kind that can carry animation state. */
function carriesAnimation(node: NodeLike): boolean {
  // `in` rather than a truthiness test: `animator` is a prototype getter that legitimately returns null for
  // a non-skinned model, and such a node still occupies a slot in the pairing below.
  return 'animator' in node
}

/**
 * Animation-bearing nodes of a subtree, in pre-order.
 *
 * Pairing old to new by POSITION is exact here, and only here: a rebuild deep-clones the very same
 * `nodeJson`, so the two trees have identical shape. Matching by name or id could not work — ids are
 * regenerated by design, and sub-mesh names repeat within one model.
 */
function animationNodesOf(node: NodeLike, out: NodeLike[] = []): NodeLike[] {
  if (carriesAnimation(node)) out.push(node)
  for (const child of node.children ?? []) animationNodesOf(child, out)
  return out
}

/** Snapshot the animation state of a placed subtree, before it is rebuilt. */
export function captureAnimationState(inst: NodeLike): PlacedAnimationState[] {
  return animationNodesOf(inst).map(n => ({
    stateMachine: n.animator?.getStateMachine() ?? null,
    mappings: n.animator?.getAnimationMappings() ?? null,
    ragdoll: n.ragdollConfig ?? null,
  }))
}

/**
 * Put a snapshot back onto a freshly rebuilt subtree, filling only what the rebuild left empty.
 *
 * **The rebuild source wins where it has an opinion**, and that asymmetry is load-bearing because the same
 * rebuild serves two very different sources. A MODEL asset never carries a state machine, so the placement's
 * has to be restored or it is lost. A TEMPLATE stores a full serialized subtree and DOES carry one — and a
 * template rebuild is usually someone propagating an edit, so overwriting it with the instance's older copy
 * would make template edits to a machine silently never reach their instances.
 *
 * Restores only what was actually there — a node that had no machine does not acquire an empty one — and
 * tolerates a length mismatch, which can only happen if the source's hierarchy changed underneath. There,
 * carrying over what still lines up beats discarding all of it.
 */
export function restoreAnimationState(inst: NodeLike, saved: PlacedAnimationState[]): void {
  if (saved.length === 0) return
  const nodes = animationNodesOf(inst)
  for (let i = 0; i < Math.min(nodes.length, saved.length); i++) {
    const s = saved[i]
    const animator = nodes[i].animator
    if (animator && s.stateMachine && !animator.getStateMachine()) animator.setStateMachine(s.stateMachine)
    if (animator && s.mappings?.length && !animator.getAnimationMappings()?.length) {
      animator.setAnimationMappings(s.mappings)
    }
    if (s.ragdoll && !nodes[i].ragdollConfig) nodes[i].ragdollConfig = s.ragdoll
  }
}
