// ---------------------------------------------------------------------------------------------------
// Per-placement animation state, carried across a rebuild.
//
// Re-instantiating a placed instance reconstructs it from its ASSET, and a model asset never carries an
// animation state machine: machines are authored in the Animation Editor and committed onto the placed
// NODE, so they exist only inside the scene or template blob. Without this, any asset edit that changes a
// model's content hash replaces every configured character in every scene with a bare one.
//
// Must stay ENGINE-FREE — structural types, no `cleo` import — so the root test suite, which cannot
// resolve the editor's `cleo` → ../dist link, can load it.
// ---------------------------------------------------------------------------------------------------

/** The subset of an Animator this needs. Structural, so a test can hand it a plain object. */
export interface AnimatorLike {
  getStateMachine(): any
  getAnimationMappings(): any[]
  setStateMachine(sm: any): void
  setAnimationMappings(mappings: any[]): void
}

/** The subset of a Node this needs. `animator` is present (possibly null) only on ModelNodes. */
export interface NodeLike {
  animator?: AnimatorLike | null
  ragdollConfig?: any
  /** ModelNodes only; `skin` exists only on an AnimatedModel. */
  model?: { skin?: { ikRig?: any } | null } | null
  children: NodeLike[]
}

/**
 * Push a model asset's IK rig onto every skinned model in a placed subtree. The ASSET owns the rig, but a
 * template bakes its own copy of the skin, so re-applying is what stops that copy outliving the panel that
 * wrote it. `undefined` must be ASSIGNED, never skipped: "the asset has no rig" has to be able to clear one.
 */
export function applyIkRig(inst: NodeLike, rig: any | null): void {
  for (const node of animationNodesOf(inst)) {
    const skin = node.model?.skin
    if (skin) skin.ikRig = rig ?? undefined
  }
}

export interface PlacedAnimationState {
  stateMachine: any | null
  mappings: any[] | null
  ragdoll: any | null
}

/** Whether a node is the kind that can carry animation state. */
function carriesAnimation(node: NodeLike): boolean {
  // `in`, not a truthiness test: `animator` is a prototype getter that returns null for a non-skinned
  // model, and such a node still occupies a slot in the pairing below.
  return 'animator' in node
}

/**
 * Animation-bearing nodes of a subtree, in pre-order.
 * Pairing old to new by POSITION is exact only because a rebuild deep-clones the very same `nodeJson`.
 * Name or id cannot be used: ids are regenerated by design and sub-mesh names repeat within one model.
 */
function animationNodesOf(node: NodeLike, out: NodeLike[] = []): NodeLike[] {
  if (carriesAnimation(node)) out.push(node)
  for (const child of node.children ?? []) animationNodesOf(child, out)
  return out
}

/** Snapshot the animation state of a placed subtree, before it is rebuilt. */
export function captureAnimationState(inst: NodeLike): PlacedAnimationState[] {
  return animationNodesOf(inst).map(n => ({
    stateMachine: n.animator?.getStateMachine() ?? null,
    mappings: n.animator?.getAnimationMappings() ?? null,
    ragdoll: n.ragdollConfig ?? null,
  }))
}

/**
 * Put a snapshot back onto a freshly rebuilt subtree, filling only what the rebuild left empty.
 *
 * **The rebuild source wins where it has an opinion.** A MODEL asset carries no state machine, so the
 * placement's must be restored; a TEMPLATE does carry one, and overwriting it would stop template edits
 * from ever reaching their instances.
 *
 * Restores only what was there, and tolerates a length mismatch by carrying over what still lines up.
 */
export function restoreAnimationState(inst: NodeLike, saved: PlacedAnimationState[]): void {
  if (saved.length === 0) return
  const nodes = animationNodesOf(inst)
  for (let i = 0; i < Math.min(nodes.length, saved.length); i++) {
    const s = saved[i]
    const animator = nodes[i].animator
    if (animator && s.stateMachine && !animator.getStateMachine()) animator.setStateMachine(s.stateMachine)
    if (animator && s.mappings?.length && !animator.getAnimationMappings()?.length) {
      animator.setAnimationMappings(s.mappings)
    }
    if (s.ragdoll && !nodes[i].ragdollConfig) nodes[i].ragdollConfig = s.ragdoll
  }
}
