import type { TypeFile } from '../nodeInspector/scriptEditor/cleoTypes'
import { hashSource, type MirrorState } from '../../utils/scriptMirror'

// Everything besides the mirrored scripts that the workspace needs to be a real TypeScript project an
// external IDE can open. All of it is hidden from the IDE's file explorer.

export const MANIFEST_PATH = '.cleo/manifest.json'
export const MANIFEST_VERSION = 1

/**
 * The bookkeeping the workspace keeps on disk, so a reconnecting session knows which file is which
 * script. Identity must never come from the filename: an IDE rename arrives as a delete plus a create,
 * so a path-derived identity mints a new asset id and drops `__scriptId` from every node using it.
 */
export type WorkspaceManifest = {
  version: number
  projectId: string
  /** scriptId -> where it lives and what it contained when we last agreed with the disk. */
  files: Record<string, { rel: string; hash: string }>
  /** Fingerprint of the declaration payload, so 98 type files are only rewritten when the engine changed. */
  typesHash: string
}

/**
 * Must mirror monacoSetup's compiler options exactly, so the IDE and the in-editor Monaco agree.
 * Monaco's `diagnosticCodesToIgnore: [2531, 2532, 18047, 18048]` needs no counterpart: those four only
 * fire under strictNullChecks, which is off.
 */
const TSCONFIG = `{
  // Generated by the Cleo editor. Edits are overwritten when the workspace is set up again.
  //
  // These options mirror the editor's in-app script editor exactly, so what you see here is what the
  // editor sees. Scripts are transpiled by sucrase at load time (types are stripped, never checked at
  // runtime), so nothing here needs to emit.
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "lib": ["ES2020", "DOM"],
    "strict": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "noImplicitThis": false,
    "skipLibCheck": true,
    "noEmit": true,
    "baseUrl": "."
  },
  // The ambient declarations are named explicitly: a "**/*" glob does not match a dot-directory.
  "include": ["**/*.ts", ".cleo/types/*.d.ts"],
  "exclude": ["node_modules"]
}
`

/**
 * Hides everything that is not a script, so the IDE's explorer shows the editor's VFS folder layout and
 * only that. `files.exclude` is a display filter, not a compiler one.
 */
const VSCODE_SETTINGS = `{
  "files.exclude": {
    "tsconfig.json": true,
    ".vscode": true,
    ".cleo": true,
    "node_modules": true,
    ".gitignore": true
  },
  "search.exclude": { "node_modules": true, ".cleo": true },
  // Saving is what pushes an edit back to the editor, so a short auto-save makes the two feel live.
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 500
}
`

// The scripts themselves are the user's to source-control; the generated scaffolding is not.
const GITIGNORE = `# Generated by the Cleo editor -- regenerated whenever the workspace is set up.
node_modules/
.cleo/
tsconfig.json
.vscode/
`

/** The static scaffolding, excluding the (much larger) declaration payload. */
export function staticScaffold(): TypeFile[] {
  return [
    { rel: 'tsconfig.json', content: TSCONFIG },
    { rel: '.vscode/settings.json', content: VSCODE_SETTINGS },
    { rel: '.gitignore', content: GITIGNORE },
  ]
}

/**
 * The full scaffold. `typesHash` lets a reconnect skip re-writing ~100 declaration files when the engine
 * has not changed. The ~725 KB declaration payload is imported dynamically to keep it out of the initial
 * bundle.
 */
export async function buildScaffold(): Promise<{ files: TypeFile[]; typesHash: string }> {
  const { workspaceTypeFiles } = await import('../nodeInspector/scriptEditor/cleoTypes')
  const types = workspaceTypeFiles()
  const typesHash = hashSource(types.map(f => `${f.rel}:${f.content.length}`).join('\n'))
  return { files: [...staticScaffold(), ...types], typesHash }
}

/** Snapshot the agreed state into the manifest that gets written next to the scripts. */
export function buildManifest(projectId: string, state: MirrorState, typesHash: string): WorkspaceManifest {
  const files: WorkspaceManifest['files'] = {}
  for (const [scriptId, entry] of state) files[scriptId] = { rel: entry.rel, hash: entry.hash }
  return { version: MANIFEST_VERSION, projectId, files, typesHash }
}

/**
 * Recover the agreed state from a manifest written by a previous session. A manifest from a different
 * project or a future version returns null; the workspace then rebuilds from the library, which is safe
 * because a full push only ever writes files.
 */
export function readManifest(manifest: unknown, projectId: string): { state: MirrorState; typesHash: string } | null {
  const m = manifest as WorkspaceManifest | null
  if (!m || typeof m !== 'object') return null
  if (m.version !== MANIFEST_VERSION) return null
  if (m.projectId !== projectId) return null
  if (!m.files || typeof m.files !== 'object') return null

  const state: MirrorState = new Map()
  for (const [scriptId, entry] of Object.entries(m.files)) {
    if (entry && typeof entry.rel === 'string' && typeof entry.hash === 'string') {
      state.set(scriptId, { rel: entry.rel, hash: entry.hash })
    }
  }
  return { state, typesHash: typeof m.typesHash === 'string' ? m.typesHash : '' }
}
