import type { TypeFile } from '../nodeInspector/scriptEditor/cleoTypes'
import { hashSource, type MirrorState } from '../../utils/scriptMirror'

// Everything the script workspace needs to be a real TypeScript project that an external IDE can open,
// beyond the mirrored scripts themselves. All of it is hidden from the IDE's file explorer, so the tree
// the user sees is exactly the editor's VFS script layout and nothing else.

export const MANIFEST_PATH = '.cleo/manifest.json'
export const MANIFEST_VERSION = 1

/**
 * The bookkeeping the workspace keeps on disk, so a session that reconnects to an existing folder knows
 * which file is which script.
 *
 * Identity deliberately does NOT come from the filename: an IDE rename arrives as a delete plus a
 * create, and deriving identity from the path would mint a new asset id and drop `__scriptId` (with the
 * per-node field values) from every node using that script.
 */
export type WorkspaceManifest = {
  version: number
  projectId: string
  /** scriptId -> where it lives and what it contained when we last agreed with the disk. */
  files: Record<string, { rel: string; hash: string }>
  /** Fingerprint of the declaration payload, so 98 type files are only rewritten when the engine changed. */
  typesHash: string
}

/**
 * Mirrors monacoSetup's compiler options exactly, so what the IDE reports is what the in-editor Monaco
 * reports. Monaco's `diagnosticCodesToIgnore: [2531, 2532, 18047, 18048]` needs no counterpart here:
 * those four only fire under strictNullChecks, which is off.
 */
const TSCONFIG = `{
  // Generated by the Cleo editor. Edits are overwritten when the workspace is set up again.
  //
  // These options mirror the editor's in-app script editor exactly, so what you see here is what the
  // editor sees. Scripts are transpiled by sucrase at load time (types are stripped, never checked at
  // runtime), so nothing here needs to emit.
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "lib": ["ES2020", "DOM"],
    "strict": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "noImplicitThis": false,
    "skipLibCheck": true,
    "noEmit": true,
    "baseUrl": "."
  },
  // The ambient declarations are named explicitly: a "**/*" glob does not match a dot-directory.
  "include": ["**/*.ts", ".cleo/types/*.d.ts"],
  "exclude": ["node_modules"]
}
`

/**
 * Hides everything that is not a script, so the IDE's explorer shows the editor's VFS folder layout and
 * only that. The files stay fully functional -- `files.exclude` is a display filter, not a compiler one.
 */
const VSCODE_SETTINGS = `{
  "files.exclude": {
    "tsconfig.json": true,
    ".vscode": true,
    ".cleo": true,
    "node_modules": true,
    ".gitignore": true
  },
  "search.exclude": { "node_modules": true, ".cleo": true },
  // Saving is what pushes an edit back to the editor, so a short auto-save makes the two feel live.
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 500
}
`

// The scripts themselves are the user's to source-control; the generated scaffolding is not.
const GITIGNORE = `# Generated by the Cleo editor -- regenerated whenever the workspace is set up.
node_modules/
.cleo/
tsconfig.json
.vscode/
`

/** The static scaffolding, excluding the (much larger) declaration payload. */
export function staticScaffold(): TypeFile[] {
  return [
    { rel: 'tsconfig.json', content: TSCONFIG },
    { rel: '.vscode/settings.json', content: VSCODE_SETTINGS },
    { rel: '.gitignore', content: GITIGNORE },
  ]
}

/**
 * The full scaffold. `typesHash` lets a reconnect skip re-writing ~100 declaration files when the engine
 * has not changed since the workspace was last opened.
 *
 * The declaration payload is ~725 KB of raw source text, imported dynamically so this feature does not
 * pin it into the initial bundle. It lands there anyway today -- CustomMaterialEditor imports
 * GlslCodeEditor statically, and that reaches monacoSetup -> cleoTypes -- so this buys nothing until that
 * chain is made lazy. It costs nothing either, and keeps the dependency honest in the meantime.
 */
export async function buildScaffold(): Promise<{ files: TypeFile[]; typesHash: string }> {
  const { workspaceTypeFiles } = await import('../nodeInspector/scriptEditor/cleoTypes')
  const types = workspaceTypeFiles()
  // Cheap and stable: the payload only changes when the engine is rebuilt.
  const typesHash = hashSource(types.map(f => `${f.rel}:${f.content.length}`).join('\n'))
  return { files: [...staticScaffold(), ...types], typesHash }
}

/** Snapshot the agreed state into the manifest that gets written next to the scripts. */
export function buildManifest(projectId: string, state: MirrorState, typesHash: string): WorkspaceManifest {
  const files: WorkspaceManifest['files'] = {}
  for (const [scriptId, entry] of state) files[scriptId] = { rel: entry.rel, hash: entry.hash }
  return { version: MANIFEST_VERSION, projectId, files, typesHash }
}

/**
 * Recover the agreed state from a manifest written by a previous session.
 *
 * A manifest from a different project (the user pointed two projects at one folder) or a future version
 * is ignored rather than trusted -- the workspace then rebuilds from the library, which is safe because
 * a full push only ever writes files.
 */
export function readManifest(manifest: unknown, projectId: string): { state: MirrorState; typesHash: string } | null {
  const m = manifest as WorkspaceManifest | null
  if (!m || typeof m !== 'object') return null
  if (m.version !== MANIFEST_VERSION) return null
  if (m.projectId !== projectId) return null
  if (!m.files || typeof m.files !== 'object') return null

  const state: MirrorState = new Map()
  for (const [scriptId, entry] of Object.entries(m.files)) {
    if (entry && typeof entry.rel === 'string' && typeof entry.hash === 'string') {
      state.set(scriptId, { rel: entry.rel, hash: entry.hash })
    }
  }
  return { state, typesHash: typeof m.typesHash === 'string' ? m.typesHash : '' }
}
