#!/usr/bin/env python3
"""Regenerate src/graphics/builtinLensDirt.ts from examples/assets/dirtmask.jpg.

The lens-dirt overlay ships INSIDE the engine rather than as a project asset, because it has to exist
in the standalone player too -- the editor-registered 'Null' texture does not, and a built-in that
silently vanished in every published game would be worse than no built-in at all.

It travels as a base64 string in a .ts module rather than as an imported image because the engine emits
no assets of its own: src/ imports .ts, .glsl/.vs/.fs and .wgsl and nothing else, and only the editor and
player builds ever bundle it. A string needs no loader anywhere.

Run from the repo root:  python tools/buildLensDirt.py
Needs Pillow. Deterministic: same input, same output.
"""

import base64
import io
import os
import sys

from PIL import Image

SOURCE = os.path.join('examples', 'assets', 'dirtmask.jpg')
TARGET = os.path.join('src', 'graphics', 'builtinLensDirt.ts')

# 1024 wide is well past what a low-frequency dirt overlay resolves, and q82 baseline keeps the streaks
# clean while landing around 55 KiB (~74 KiB once base64'd). Baseline, not progressive: a progressive
# JPEG decodes more slowly and nothing here streams.
WIDTH = 1024
QUALITY = 82

HEADER = '''// The built-in lens-dirt overlay: the smudges and streaks a real lens has, which catch bloom and lens
// flare and are invisible everywhere else.
//
// GENERATED by tools/buildLensDirt.py from examples/assets/dirtmask.jpg -- do not edit by hand.
//
// It lives in the engine rather than in a project because it has to exist in the standalone player as
// well as the editor. The editor registers its 'Null' fallback into `TextureManager` at boot and the
// player does not, so a built-in registered that way would work in the editor and silently disappear
// from every published game. This module has no such asymmetry: it is imported, so it is simply there.
//
// Base64 rather than an image import because the engine emits no assets of its own and src/ imports no
// images -- see the generator script for the full reasoning.

/** {width}x{height} baseline JPEG, quality {quality}. Decoded lazily; see `Renderer._lensDirtTexture`. */
export const BUILTIN_LENS_DIRT_MIME = 'image/jpeg';

export const BUILTIN_LENS_DIRT_BASE64 =
'''


def main() -> int:
    if not os.path.isfile(SOURCE):
        print(f'source not found: {SOURCE}', file=sys.stderr)
        return 1

    image = Image.open(SOURCE).convert('RGB')
    height = round(image.height * WIDTH / image.width)
    resized = image.resize((WIDTH, height), Image.LANCZOS)

    buffer = io.BytesIO()
    resized.save(buffer, 'JPEG', quality=QUALITY, optimize=True, progressive=False)
    encoded = base64.b64encode(buffer.getvalue()).decode('ascii')

    # Wrapped at 100 columns so the file is diffable and no editor chokes on one enormous line.
    chunk = 96
    lines = [encoded[i:i + chunk] for i in range(0, len(encoded), chunk)]
    body = '\n'.join(f"    '{line}' +" for line in lines[:-1])
    body += f"\n    '{lines[-1]}';\n"

    header = HEADER.format(width=WIDTH, height=height, quality=QUALITY)
    with io.open(TARGET, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(header + body)

    print(f'{TARGET}: {WIDTH}x{height}, {buffer.getbuffer().nbytes} bytes '
          f'-> {len(encoded)} base64 chars')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
