#!/usr/bin/env node
// Generates CHANGELOG.md sections from git history.
//
// One classifier serves both the one-time backfill of the pre-versioning history and every future
// release, so a commit is bucketed the same way whenever it is read. That matters because the BASELINE
// VERSION NUMBER ITSELF was derived from these counts: v1.0.<features>.<minor> over the whole history.
// If the classifier changes, `--counts` no longer reproduces the baseline and the number is a lie.
//
// Two rules, in order:
//   1. Conventional Commits -- `feat:` is a feature, `fix|refactor|perf|style|chore|docs|test|build|ci`
//      are minor, and a `!` marker or a BREAKING CHANGE trailer overrides both.
//   2. Everything else. Roughly half this repo predates the convention ("pointlights", "scene graph",
//      "physics editor"), so those are bucketed by leading verb: a maintenance verb means minor, and
//      anything else is describing a new capability, which means feature.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHANGELOG = join(ROOT, 'CHANGELOG.md');

const CONVENTIONAL = /^(feat|fix|refactor|perf|style|chore|docs|test|build|ci)(\([^)]*\))?(!)?:/i;
const MINOR_TYPES = new Set(['fix', 'refactor', 'perf', 'style', 'chore', 'docs', 'test', 'build', 'ci']);
const MINOR_VERBS = /^(refactor|fix|remove|update|clean|rename|tweak|improve|optimi|correct|revert|merge|delete|move|minor|small|typo)/i;

const HEADINGS = { breaking: 'Breaking changes', feature: 'Features', minor: 'Fixes & refactors' };

export function classify(subject, body = '') {
    const breaking = /(^|\n)BREAKING[ -]CHANGE/.test(body);
    const m = subject.match(CONVENTIONAL);
    if (m) {
        if (m[3] || breaking) return 'breaking';
        return MINOR_TYPES.has(m[1].toLowerCase()) ? 'minor' : 'feature';
    }
    if (breaking) return 'breaking';
    return MINOR_VERBS.test(subject) ? 'minor' : 'feature';
}

const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

// %x00 between fields and %x01 between records: commit bodies contain newlines and every printable
// separator you might reach for, so the delimiters have to be characters git will never emit itself.
function commits(range) {
    const out = git('log', '--no-merges', '--pretty=format:%h%x00%s%x00%b%x01', ...(range ? [range] : []));
    return out
        .split('\x01')
        .map((r) => r.trim())
        .filter(Boolean)
        .map((r) => {
            const [sha, subject, body = ''] = r.split('\x00');
            return { sha, subject, body, kind: classify(subject, body) };
        })
        // Release commits are bookkeeping this tool created; they are not part of anyone's changelog.
        .filter((c) => !/^chore\(release\):/i.test(c.subject));
}

function tally(list) {
    return list.reduce((acc, c) => ((acc[c.kind] = (acc[c.kind] || 0) + 1), acc), { breaking: 0, feature: 0, minor: 0 });
}

// Newest first within each group -- the same order `git log` gave them.
function section(version, list, date) {
    const lines = [`## v${version} — ${date}`, ''];
    for (const kind of ['breaking', 'feature', 'minor']) {
        const group = list.filter((c) => c.kind === kind);
        if (!group.length) continue;
        lines.push(`### ${HEADINGS[kind]}`, '');
        for (const c of group) lines.push(`- ${c.subject} (${c.sha})`);
        lines.push('');
    }
    if (list.length === 0) lines.push('_No changes._', '');
    return lines.join('\n');
}

const HEADER = `# Changelog

Versions follow the scheme \`1.x.y.z\`, where **x** counts breaking changes, **y** counts major features
and **z** counts fixes and refactors. The leading \`1.\` is a fixed product-line prefix; \`package.json\`
stores the remaining \`x.y.z\` because npm requires three-component semver.

Sections are generated by \`tools/changelog.mjs\` from the commits between two release tags.

`;

function readTail() {
    if (!existsSync(CHANGELOG)) return '';
    const text = readFileSync(CHANGELOG, 'utf8');
    const at = text.indexOf('\n## ');
    return at === -1 ? '' : text.slice(at + 1);
}

// The latest existing tag. Version-sorted rather than date-sorted so a hotfix tagged out of order does
// not become the baseline for the next range.
function previousTag() {
    const tags = git('tag', '--list', 'v*', '--sort=-v:refname').split('\n').map((t) => t.trim()).filter(Boolean);
    return tags[0] || null;
}

const today = () => git('log', '-1', '--pretty=format:%ad', '--date=short').trim();

function main() {
    const [mode, arg, notesOut] = process.argv.slice(2);

    if (mode === '--counts') {
        const t = tally(commits(null));
        console.log(`features : ${t.feature}\nminor    : ${t.minor}\nbreaking : ${t.breaking}\n\nbaseline  v1.${t.breaking}.${t.feature}.${t.minor}`);
        return;
    }

    if (mode === '--backfill') {
        // `arg` is the baseline the package.json files were set to. Asserting it against the tally is the
        // whole point: a mismatch means the version number does not describe the history it claims to.
        if (!arg) throw new Error('usage: node tools/changelog.mjs --backfill <version>');
        const list = commits(null);
        const t = tally(list);
        const derived = `1.${t.breaking}.${t.feature}.${t.minor}`;
        if (derived !== arg) {
            console.error(`Baseline mismatch: history classifies as v${derived}, but v${arg} was given.`);
            process.exit(1);
        }
        writeFileSync(CHANGELOG, HEADER + section(arg, list, today()));
        console.log(`CHANGELOG.md: backfilled ${list.length} commits as v${arg}`);
        return;
    }

    if (mode === '--release') {
        if (!arg) throw new Error('usage: node tools/changelog.mjs --release <version> [notes-out]');
        const prev = previousTag();
        const list = commits(prev ? `${prev}..HEAD` : null);
        const body = section(arg, list, today());
        writeFileSync(CHANGELOG, HEADER + body + '\n' + readTail());
        // Notes for `gh release create --notes-file`: the section without its own version heading, which
        // the Release page already shows as the title.
        if (notesOut) writeFileSync(notesOut, body.split('\n').slice(2).join('\n'));
        console.log(`CHANGELOG.md: v${arg} — ${list.length} commits since ${prev || 'the beginning'}`);
        return;
    }

    console.error('usage: node tools/changelog.mjs --counts\n       node tools/changelog.mjs --backfill <version>\n       node tools/changelog.mjs --release <version> [notes-out]');
    process.exit(2);
}

// Only when run as a script -- `classify` is exported so the tally can be inspected from elsewhere
// without the CLI firing on import.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
